# Generated by Django 4.2.6 on 2023-10-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0006_hostel_friday_menu_hostel_monday_menu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='friday_menu',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='monday_menu',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='saturday_menu',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='sunday_menu',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='thursday_menu',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='tuesday_menu',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='wednesday_menu',
            field=models.TextField(blank=True),
        ),
    ]
