# Generated by Django 4.2.6 on 2023-10-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0007_alter_hostel_friday_menu_alter_hostel_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='photo',
            field=models.ImageField(null=True, upload_to='documents/'),
        ),
    ]
