# Generated by Django 4.2.6 on 2023-10-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0012_complaint_status_alter_complaint_id_alter_course_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='due_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
