# Generated by Django 4.2.6 on 2023-11-05 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0020_alter_complaint_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='warden',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='warden',
            name='phone_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
