# Generated by Django 4.2.6 on 2023-11-05 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0023_alter_student_no_dues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='no_dues',
            field=models.BooleanField(default=True),
        ),
    ]
