# Generated by Django 4.2.6 on 2023-11-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0024_alter_student_no_dues'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='status',
        ),
        migrations.AlterField(
            model_name='room',
            name='vacant',
            field=models.BooleanField(default=True),
        ),
    ]
